@host = http://127.0.0.1:8000

#1) List all avaiable products in the system
GET {{host}}/products

###

#2) Create a new order
POST {{host}}/create_order 
Content-Type: application/json

{
    "timestamp": "2023-07-09T03:24:31.202169",
    "items": [
        {
            "product_id": 1,
            "bought_quantity": 4
        },
        {
            "product_id": 7,
            "bought_quantity": 1
        },
        {
            "product_id": 13,
            "bought_quantity": 2
        },
        {
            "product_id": 14,
            "bought_quantity": 7
        }
    ],
    "total_amount": 3210.05,
    "user_address": {
        "city": "Kolkata",
        "country": "India",
        "zip_code": "98072"
    }
}

###

#3) Fetch all orders from the system (Also implement pagination using limit and offset)
GET {{host}}/orders?limit=1&offset=22



###

#4) Get a specific order using order_id
@order_id = 22
GET {{host}}/orders/{{order_id}}


###


#5) Update a product (using product_id) when updating the available quantity for the product
@product_id = 25
PUT {{host}}/products/{{product_id}}?quantity=1


###

#6) Adds a new product 
POST {{host}}/add_product
Content-Type: application/json

{
    "Name": "Apple Macbook-3",
    "Price": 1889000,
    "Qty": 9
}



